const express = require('express')
const {testUploadProduct,getProduce,deleteProduct} = require('../Controller/Farmers/product')
const {profile, updateProfile} = require('../Controller/Farmers/profile')
const { authenticateFarmerToken } = require('../middlewares/authenticateToken')
const router = express.Router()
router.get('/fM/profile/:Id',profile)
router.delete('/deleteProduce/:produceId',deleteProduct)
router.put('/updateprofile/:Id',updateProfile)
router.get('/produce/:Id',getProduce)
router.post('/testProduce/:Id',testUploadProduct)
module.exports = router