GET http://localhost/admin/allConsumer/6554cc167d7baadea3505b5c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTRjYzE2N2Q3YmFhZGVhMzUwNWI1YyIsInVzZXJuYW1lIjoidGltb3RoeSIsIkFkbWluSWQiOiJmNmU0MTBiYjFjZjgxZDgzZjE3NmQ3MmQwZTBiNmJlMCIsImVtYWlsIjoidGltb3RoeS5hdmVsbC5vbGF0dW5kZUBnbWFpbC5jb20iLCJpYXQiOjE3MDA0NzUwODd9.xQ1NxCkipv7z2ZOL32R1X5MMwL62BJe2nflyfAzyCd4

###
GET http://localhost/admin/allFarmer/6554cc167d7baadea3505b5c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTRjYzE2N2Q3YmFhZGVhMzUwNWI1YyIsInVzZXJuYW1lIjoidGltb3RoeSIsIkFkbWluSWQiOiJmNmU0MTBiYjFjZjgxZDgzZjE3NmQ3MmQwZTBiNmJlMCIsImVtYWlsIjoidGltb3RoeS5hdmVsbC5vbGF0dW5kZUBnbWFpbC5jb20iLCJpYXQiOjE3MDA0ODUyMzJ9.UZtv2c2YMK9xh3mNAweMrdpd-PF-GvcqpEPFIbfk31g

###


###
POST http://localhost/admin/banConsumer/6555dd152d7e2cd8d0296f28/6554cc167d7baadea3505b5c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTRjYzE2N2Q3YmFhZGVhMzUwNWI1YyIsInVzZXJuYW1lIjoidGltb3RoeSIsIkFkbWluSWQiOiJmNmU0MTBiYjFjZjgxZDgzZjE3NmQ3MmQwZTBiNmJlMCIsImVtYWlsIjoidGltb3RoeS5hdmVsbC5vbGF0dW5kZUBnbWFpbC5jb20iLCJpYXQiOjE3MDA0ODUyMzJ9.UZtv2c2YMK9xh3mNAweMrdpd-PF-GvcqpEPFIbfk31g

###
POST http://localhost/admin/banFarmer/6555dd152d7e2cd8d0296f28/6554cc167d7baadea3505b5c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTRjYzE2N2Q3YmFhZGVhMzUwNWI1YyIsInVzZXJuYW1lIjoidGltb3RoeSIsIkFkbWluSWQiOiJmNmU0MTBiYjFjZjgxZDgzZjE3NmQ3MmQwZTBiNmJlMCIsImVtYWlsIjoidGltb3RoeS5hdmVsbC5vbGF0dW5kZUBnbWFpbC5jb20iLCJpYXQiOjE3MDA0ODUyMzJ9.UZtv2c2YMK9xh3mNAweMrdpd-PF-GvcqpEPFIbfk31g

